---
- name: install php7.0-cli
  apt: pkg=php7.0-cli state=latest

# You may need to symlink 'ln -s /etc/php/7.0/mods-available /etc/php/mods-available'
# for some modules to install properly
- name: install php7 libraries
  apt: pkg={{item}} state=latest
  with_items:
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-mysql
    - php7.0-readline
    - php7.0-json
    - php7.0-xml
    - php7.0-opcache
    - php7.0-gd
    - php7.0-redis
    - php7.0-mbstring
    - php7.0-zip
    - php7.0-phpdbg
    # - php7.0-xdebug
    # - php7.0-memcache
    # - php7.0-memcached

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- file: path=~/.composer state=directory mode=0755

- name: add github auth token
  template:
    src: composer-auth.json
    dest: "~/.composer/auth.json"
    backup: no

- name: install php7-cli config file
  template: backup=no
            dest=/etc/php/7.0/cli/php.ini
            src=php-cli.ini
            owner=root
            group=root
            mode=0644

- name: install php7.0-fpm
  apt: pkg=php7.0-fpm state=latest

- name: copy php7.0-fpm php.ini
  template: backup=no
            dest=/etc/php/7.0/fpm/php.ini
            src=php-fpm.ini
            owner=root
            group=root
            mode=0644
  notify:
    - restart php-fpm

- name: copy php7.0-fpm config
  template: backup=no
            dest=/etc/php/7.0/fpm/php-fpm.conf
            src=php-fpm.conf
            owner=root
            group=root
            mode=0644
  notify:
    - restart php-fpm

- name: copy php7.0-fpm www.conf
  template: backup=no
            dest=/etc/php/7.0/fpm/pool.d/www.conf
            src=php-fpm-www.conf
            owner=root
            group=root
            mode=0644
  notify:
    - restart php-fpm

- stat: path=/etc/nginx
  register: nginx_path

- name: copy php-fastcgi.conf to /etc/nginx
  template: backup=no
      dest=/etc/nginx/php-fastcgi.conf
            src=php-fastcgi.conf.j2
            owner=root
            group=root
            mode=0644
  when: nginx_path.stat.exists
  notify:
    - restart nginx
